### ISSUE TITLE
rationalize the behaviour of filelocks in tests

### ISSUE THREAD

**Issue by Gankra** [mozilla/cargo-vet#130]
--readonly-lockless is a hack to avoid concurrent tests from blowing up when grabbing locks.

We should either:

* Implement proper blocking locks so the tests auto-serialize
* Enforce --num-threads=1 or whatever
* Somehow fold --readonly-lockless semantics into normal --locked 
  * I think this is wrong, --locked does want to avoid filelocks to avoid another instance writing over what you're reading.
  * Also unclear if --locked should be allowed to mutate some state? Right now it's ambiguous in that I think it defacto can't change state but still commits results, which at very least can `fmt`
* Properly rationalize and define the semantics of lockless mode
  * Right now it's not actually readonly, can trigger fetches to perform suggests
  * Should it omit those results or error out if it would need a fetch...?
  * Should it be a "fully testing" mode and not actually be allowed to access the global cache at all (require a manual --diff-cache, no writebacks?)

**Comment by mystor** [comment]
`--readonly-lockless` isn't a thing anymore as of #161, so I think we can close this
