### ISSUE TITLE
implement guessing heuristics for cargo vet certify

### ISSUE THREAD

**Issue by bholley** [mozilla/cargo-vet#143]
These were outlined in https://github.com/bholley/cargo-vet/issues/85#issuecomment-1133091909 and https://github.com/bholley/cargo-vet/issues/85#issuecomment-1133374812 , but not implemented in #140.

**Comment by Gankra** [comment]
Ah I regarded the guessing stuff as more p2-nice-to-have.

Part of the question for the really stateful stuff is "where" it should go and how hard we should try to remember different things and for how long.

The simplest solution I could think of was:

* in the global temp-cache, create a recent_commands.json
  * contains the last suggest (in a more machine-readable form)
  * contains the last inspect/diff
  
Both of those commands access that cache so they already need to get a lock to the global cache. Then when we certify we check if there's a recent inspect/diff, and then check if it was suggested, and if so, what criteria were suggested.

That said I think we still want to have some sort of pre-prompt of "is this guess right?"

Possibly it's the current interactive prompt but the guess is just filled in so if it's right you just mash enter?

**Comment by bholley** [comment]
That generally seems reasonable, except that I'm not sure it's worth the complexity of trying to cache the most-recent vet and suggest calls — seems easier to just invoke them internally (perhaps with some way to scope it to the computations we care about — just that crate, and none of the diffcache stuff).

**Comment by Gankra** [comment]
if we already need to cache what the last inspect/diff call was, it seems easier (and faster) at that point to just be consistent and cache the suggest in the same place.

**Comment by bholley** [comment]
It's also a question of accuracy. It's conceivable that the impetus to perform/certify the audit did not come from a recent invocation of `vet` or `suggest` on the local machine. I would intuitive inspect `cargo vet certify foo 1.2` not to depend on some magically-cached possibly-stale artifact, whereas it's more understandable that bare `cargo vet certify` would.

**Comment by Gankra** [comment]
hmm so do you want magic to be basically binary? all or nothing?

**Comment by bholley** [comment]
When criteria aren't specified, `cargo vet` should guess them based on the tree state (i.e. an internal `vet`/`vet suggest`). When the crate+version is not specified, `cargo vet` should guess them based on history (i.e. last call to inspect or diff).

**Comment by Gankra** [comment]
One reason to prefer a previous invocation is because `suggest` vs `suggest --guess-deeper` is a pretty significant difference and we can't know which they used without literally just remembering. It would be annoying to do the expensive `--guess-deeper` and hang `certify` for no reason
