### ISSUE TITLE
certify should explicitly prompt for notes

### ISSUE THREAD

**Issue by bholley** [mozilla/cargo-vet#144]
@glandium makes the point that, more often than not, people will have notes to add when certifying an audit, and that we should probably encourage doing so. As such perhaps after the "yes" we can prompt for "notes"?

**Comment by glandium** [comment]
Should the note prompt be after the "type yes to certify" prompt?

**Comment by Gankra** [comment]
the ux juuuust got redesigned in #180 so you might want to check that out
