### ISSUE TITLE
`cargo vet fmt` unformats multiline TOML strings

### ISSUE THREAD

**Issue by str4d** [mozilla/cargo-vet#155]
I added the example `crypto-reviewed` criteria from the book to my `audits.toml` file:
https://github.com/mozilla/cargo-vet/blob/87394b660f7f2ba5ac0f70ec2cc00dbbba6ae720/book/src/audit-criteria.md?plain=1#L17-L21

`cargo vet fmt` transforms this into:
```diff
diff --git a/qa/supply-chain/audits.toml b/qa/supply-chain/audits.toml
index 031666a845..9b5f79ac75 100644
--- a/qa/supply-chain/audits.toml
+++ b/qa/supply-chain/audits.toml
@@ -2,10 +2,7 @@
 # cargo-vet audits file
 
 [criteria.crypto-reviewed]
-description = '''
-The cryptographic code in this crate has been reviewed for correctness by a
-member of a designated set of cryptography experts within the project.
-'''
+description = "The cryptographic code in this crate has been reviewed for correctness by a\nmember of a designated set of cryptography experts within the project.\n"
 
 [audits]
 

```

**Comment by Gankra** [comment]
I expect whatever fix for this comes will be the same as #103

**Comment by bholley** [comment]
Heh yeah — the toml-rs serialization deficiencies have been driving me nuts. I've been willing to live with it because the issues are largely cosmetic, but we should fix it soon.

**Comment by Gankra** [comment]
Ah there is a flag(s) for this already that we could set: https://docs.rs/toml/latest/toml/ser/struct.Serializer.html#method.pretty_string
