### ISSUE TITLE
Example GitHub Actions CI workflow is broken

### ISSUE THREAD

**Issue by str4d** [mozilla/cargo-vet#156]
https://mozilla.github.io/cargo-vet/configuring-ci.html gives an example CI workflow:
https://github.com/mozilla/cargo-vet/blob/e5c28ce5e4794afbbaa2accf57f5c952ef65027d/book/src/configuring-ci.md?plain=1#L11-L22

This fails with:
```
Error: 'cargo metadata' exited unsuccessfully
Caused by:
    `cargo metadata` exited with an error: error: failed to download `CRATE_NAME VERSION`
    Caused by:
      attempting to make an HTTP request, but --frozen was specified
Location:
    src/main.rs:249:10
```

The error is caused by `cargo vet --locked` implying `cargo metadata --frozen`:
https://github.com/mozilla/cargo-vet/blob/e5c28ce5e4794afbbaa2accf57f5c952ef65027d/src/main.rs#L234-L249

The workflow as-written never tries to build the project, and because GitHub Actions builders don't maintain crates.io registry caches, the dependency sources are not available.

The example workflow should include a `cargo fetch --locked` or similar to ensure that everything `cargo vet --locked` needs is present.

**Comment by str4d** [comment]
It wasn't immediately clear to me _why_ `cargo vet --locked` needs to imply `cargo metadata --frozen`. When reading the book, I interpreted `cargo vet --locked` as locking the `supply-chain/imports.lock` file, pinning the foreign dependencies. It was only after encountering the error that I noticed the `--locked` flag is documented as:
```
--locked
    Do not pull in new "audits" and try to avoid the network
```
It might be more obvious to people who are used to `cargo`, if this behaviour was split into separate `--locked` and `--frozen` flags.

**Comment by str4d** [comment]
It took me several attempts to get this right in my own CI workflow, because I initially thought `cargo check --locked` would work, but that only fetches dependencies for the current target, not every target as `cargo vet` requires. Fortunately `cargo fetch --locked` does precisely what is necessary, so this should just be a single-line change to the example.

**Comment by bholley** [comment]
I'm persuaded that we want separate --locked and --frozen for network-connected and network-isolated (+vendored) CI. I'll make a PR.
