### ISSUE TITLE
criteria should be namespaced

### ISSUE THREAD

**Issue by Gankra** [mozilla/cargo-vet#16]
Consider two projects, A and B, who mutually trust eachother and import eachother's audits.

We are trying to validate Serde v10

A defines:
* 5: "reviewed"
* 8->9: "reviewed"
* B_criteria_map: "super_audited" -> "reviewed"

B defines:
* 5->8: "super_audited" 
* 9->10: "audited"
* A_criteria_map: "reviewed" -> "audited"
* "super_audited" implies "audited"

Note how the two projects aren't agreeing on a bijective mapping -- B thinks "reviewed" is as good as audited, while A thinks you need to be super_audited to reach that bar.

When B goes to vet v10, it follows a chain of "audited" and concludes v10 is "audited" ✅

When A goes to vet v10, it makes it only to v9 on "reviewed" and then can't make progress ❌

This sucks, but ok sure they're supposed to agree to cooperate and this can be resolved. Now add in dependency_criteria -- unless there is a proper bijection, foreign audits with dependency_criteria are gibberish in your own terminology, so you need to either reject audits that can't be fully mapped into your terminology (and even then they might fail), or, I guess, try to track the audit resolution from the perspective of you and every foreign import your include **at the same time** and try to... somehow... make sense of that? This... gets messy very quickly.

And this is to say nothing of just, a third-party C trying to import A and/or B and make any sense of what's going on! Can they figure out v10 is "audited" but not "reviewed"? Are they actually expected to do the resolution from the simultaneous perspective of every file they include?

It seems like if your resolution chain for some crate involves a mix of local and foreign constraints, things get very wobbly and bad very quickly. It would be good to know: 

* "how hard" we are expect to try to resolve criteria in these mixed situations
* under what conditions we're allowed to discard audits as "gibberish from my perspective"
* if we should try to signal/log when we do this
* some recommended "best practices" for orgs to follow to avoid things becoming impossible soup

**Comment by Gankra** [comment]
(I consider this a reasonable argument for taking #15 a bit more seriously, to make resolution more reliable)

**Comment by Gankra** [comment]
Oh similar problem I suppose: 

A: 
* 5: unaudited 

B: 
* 4: unaudited
* 4->6: "super_audited"

Is A allowed to conclude v6 is "reviewed"? It seems strange to reject v6 on the basis that your "whatever I haven't looked at it" entry is **too new**?

**Comment by bholley** [comment]
They key point is that criteria_map lives in config.toml, not in audits.toml. Every project records audits in its own namespace, and can optionally map audits from other project's namespace into that namespace for its own purposes, but that mapping does not impact other consumers importing the relevant audits.toml.

**Comment by Gankra** [comment]
I'm not sure that really solves the issues I describe here. Well, it mostly just means "project C is absolutely screwed if it doesn't know exactly how to map A's and B's definitions coherently enough to get similar results to them".

**Comment by Gankra** [comment]
Fleshing out the problem I see with foreign dep_criteria a bit more:

A:
* B_criteria_map: "super_audited" -> "reviewed"

B:
* Serde: "super_audited" 
  * if SerdeBuildHelper: "audited"
* SerdeBuildHelper: "audited"

B clearly sees Serde is super_audited, which would imply it's "reviewed" to A, but can A actually understand this? As I see it, there are 3 options for processing foreign audits:

1. Convert all things into your terminology immediately
   * If an entry loses (all?) its criteria as a result, discard it as meaningless
   * I guess maybe discard anything where dependency_criteria wasn't fully mappable because it's sketchy..? 
   * result: A will drop all the entries, B is effectively empty

2. The same as 1, but A is recommended to keep its own "dummy" entries for B's criteria
   * Kinda a gross violation of concerns
   * result: A will properly understand B

3. The resolver is expect to actually perform resolution in the semantics of the local audits.toml *and* the foreign ones at the same time 
   * I guess by just having a `Vec<Vec<Criteria>>` and unioning/intersecting across the entire thing...?
   * This sounds horribly complex and expensive
   * I honestly can't quite fit this in my head at the moment

4. ??? Some mystery solution where we maximally resolve each file on its own and then merge results ???
   * My brain insists this is a thing, but I don't think it is
   * Runs into issues if A has a different version of SerdeBuildHelper that it says is "reviewed"
   * (B's resolution won't see this, so A's results can't help it solve the dependency_criteria)

I've been reworking the algorithm to factor in criteria/maps/dependency_criteria, and my current inclination for mvp sanity is to just discard any foreign audits that have dependency_criteria, because they are actually a nightmare to think about.

**Comment by bholley** [comment]
I believe we decided to resolve this by treating all criteria as namespaced. So all foreign criteria are comprehensible to the system (allowing proper resolution with respect to `dependency_criteria`), but they have no relationship to the criteria used for local audits and policy enforcement unless specified in `criteria_map`.

Morphing this bug to be about implementing that. The book already reflects this.

**Comment by Gankra** [comment]
closing in favour of #240
