### ISSUE TITLE
Encourage people who find vulnerabilities in their audits to report them to the rustsec advisory-db

### ISSUE THREAD

**Issue by alex** [mozilla/cargo-vet#164]
https://github.com/rustsec/advisory-db/ is a community curated database of rust crate vulnerabilities.

It'd be good if cargo-vet encouraged people to submit them there (and to upstream of course) when they identify vulnerabilities. In practice this probably means a sentence in the docs or in the CLI output.

**Comment by bholley** [comment]
Yes that's a good idea. Most direct place to print a message would probably be when invoking `record-violation`.
