### ISSUE TITLE
investigate whether we should be using libgit2 over git-as-a-binary

### ISSUE THREAD

**Issue by Gankra** [mozilla/cargo-vet#175]
We use git-as-a-binary for:

* get_user_info (global config user.email/user.name)
* diffing

This was done as just a quick-and-dirty thing while we were prototyping. It's possible we should be using libgit2 directly.

**Comment by mystor** [comment]
I imagine we don't need the full functionality of libgit2, and can probably get away with just continuing to use the CLI, at least for now. The main thing which I could see being nice to move in-tree would be the diffing, but even if we pull in a library for that I think it'd be fine to use git to read basic configuration information.

Something like my (ab-?)use of GIT_EDITOR in #180 wouldn't be possible without the git CLI being available.

**Comment by bholley** [comment]
I suppose I'll close this for now and we can reopen if we see a need.

**Comment by mystor** [comment]
I do think this is more compelling as an option now that we depend on `git2` through `crates-index`, so we'd not be adding a new dependency.
