### ISSUE TITLE
Consider storing the cache in $XDG_CACHE_HOME on platforms where that's applicable

### ISSUE THREAD

**Issue by mystor** [mozilla/cargo-vet#184]
Currently the cache is stored in the system's temporary directory. On platforms where XDG is relevant, we could consider using `$XDG_CACHE_HOME` instead. 

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
>  `$XDG_CACHE_HOME` defines the base directory relative to which user-specific non-essential data files should be stored. If `$XDG_CACHE_HOME` is either not set or empty, a default equal to `$HOME/.cache` should be used.

**Comment by glandium** [comment]
The `dirs` crate has a `cache_dir` that uses a proper cache directory on all platforms.

**Comment by glandium** [comment]
> become incredibly hungry for downloads and we could genuinely build up an enormous never-GC'd cache in there.

The cargo registry is also a never-GC'd cache, isn't it?

**Comment by Gankra** [comment]
correct, but suggest has more hungry demands over time. Every audit you build up over time becomes another candidate to do a delta-audit off of, and so in the limit we need to fetch every version ever mentionned in your audits.toml. It wouldn't be surprising to have 100+ versions of just one crate after a few years. Now multiply that by the 300 crates in your project... yikes.

**Comment by mystor** [comment]
Perhaps that's a motivation for an eventual `cargo vet gc` which cleans up downloads of old versions of crates which have already been updated? We could theoretically stash an index of each downloaded crate along with its last accessed time, and clean up stuff which hasn't been touched in a while (a month?). If we make it cheap enough, we could potentially even do it after most commands like git does.

**Comment by bholley** [comment]
I think my proposal here is:
(1) Stash everything in ~/.cargo-vet
(2) Have `suggest` store the last time a crate was used (directly, or implicitly via the diffcache).
(3) Implement `cargo vet gc`, which removes anything not used in the last month.
(3) Have any command that flushes to disk do an implicit gc.

**Comment by bholley** [comment]
Resolving this in favor of #191.
