### ISSUE TITLE
Book suggests installing `cargo-vet` from crates.io, which is currently just a placeholder crate

### ISSUE THREAD

**Issue by vincentdephily** [mozilla/cargo-vet#187]
https://mozilla.github.io/cargo-vet/install.html says `Installing cargo vet can be done through Cargo $ cargo install cargo-vet` but https://crates.io/crates/cargo-vet is just a "hello world" placeholder.

Please either release something on crates.io, or change the book to instruct building from git.

**Comment by mystor** [comment]
See-also #148

The book does include a note telling the user to install through `cargo install --path .` on the page you linked, however perhaps it could be made more visible.

**Comment by bholley** [comment]
Sure, I can move the note further up.
