### ISSUE TITLE
Store cargo vet data in the OS cache directory and GC it

### ISSUE THREAD

**Issue by bholley** [mozilla/cargo-vet#191]
Supersedes #184.

My proposal here is:
(1) Stash everything in the dir crate's `cache_dir()`
(2) Have suggest store the last time a crate was used (directly, or implicitly via the diffcache).
(3) Implement a gc algorithm, which removes anything not used in the last month.
(4) Have any command that flushes to disk do an implicit gc.

**Comment by glandium** [comment]
You should use XDG directories.

**Comment by bholley** [comment]
Morphing after having been persuaded that the OS cache directory is the right thing.

**Comment by mystor** [comment]
We'll probably want to build this on top of #185, but with a GC algorithm, perhaps based on mtimes.
