### ISSUE TITLE
Minimize reliance on command history for certify guessing

### ISSUE THREAD

**Issue by bholley** [mozilla/cargo-vet#192]
Now that we're making --guess-deeper the default in #190, there's no semantic ambiguity or performance risk in having `cargo vet certify` sometimes fall back to the suggest algorithm. As such we should just do that, and reduce the magical out-of-band reliance on previously-executed commands.

The only thing that should rely on that is bare `cargo vet certify`, which needs to guess which crate you're talking about.

**Comment by Gankra** [comment]
Note that there is still a semantic ambiguity -- whether you are going off of a `vet` or a `vet suggest`. However if we're willing to just throw infinite time at the problem we can just check if `vet` passes, and if it does, use `vet suggest`.

**Comment by bholley** [comment]
> However if we're willing to just throw infinite time at the problem we can just check if `vet` passes, and if it does, use `vet suggest`.

Yep that sounds right.

**Comment by mystor** [comment]
We'll probably need to change how suggest is implemented slightly, as if we're running suggest within another command we can't do the trick we currently do of mutating the store to remove unaudited dependencies, and then not comitting those changes back.
