### ISSUE TITLE
Interactively display criteria and instructions when invoking inspect/diff

### ISSUE THREAD

**Issue by bholley** [mozilla/cargo-vet#200]
When someone encounters a cargo-vet failure for the first time, the output will tell them to run `inspect` or `diff` and indicate which criteria to audit for, but there's never an opportunity for the person to read the actual criteria until they're done with the audit and trying to certify. This is obviously not ideal for first-timers.

My proposal here is that `inspect` and `diff` should infer the criteria (with the same algorithm that `certify` uses), and print the description(s) to the terminal, perhaps along with some additional helpful instructions ("these audits impact the ecosystem", "ask for help if you're not sure", etc). The user then hits `enter` to continue with the inspect/diff (which currently results in more activities in the terminal, but will soon open up a web inspection view unless --local is passed).

We can then add a --non-interactive flag to skip the above.

**Comment by mystor** [comment]
Once #210 has landed, there will be a convenient function which factors the criteria guessing part of `certify` out which we can build on top of to add this functionality to `inspect` and `diff`.

**Comment by mystor** [comment]
I have some partial local patches for this, but I'm out tomorrow & friday so I'll post them on Monday after rebasing on top of whatever error changes @Gankra is making.
