### ISSUE TITLE
Log explanations for long-running pauses

### ISSUE THREAD

**Issue by mystor** [mozilla/cargo-vet#209]
Sometimes cargo-vet will pause for a short while due to running an I/O operation. Often these pauses are frequent and short enough that we don't need to mention them in the UI, but if they are running for a long enough amount of time, we should consider logging a notice to the user that we're doing something which might take a bit. 

This could be done with an async timer running alongside whatever long operation we're performing which will log if the timer expires before the operation is complete. We'd likely want this for anything doing network access (e.g. running `cargo metadata`, fetching audits from another repository or downloading crates from crates.io) so that the user isn't confused why `cargo vet` is taking a bit longer this time.

If we build up a language for how to communicate these indeterminate pauses, we'll likely also want to use it for the log messages emitted when waiting for a file lock due to another running instance of `cargo vet`.

**Comment by bholley** [comment]
I do think this is particularly confusing on first-run (when we need to cache a bunch of stuff) and when the cargo cache is stale (because then cargo metadata can hand for a long time while doing git fetches), so bumping this up.
