### ISSUE TITLE
Consider allowing specifying specific versions for `audit-as-crates-io` in edge-case scenarios.

### ISSUE THREAD

**Issue by mystor** [mozilla/cargo-vet#215]
In the majority of cases, an `audit-as-crates-io` entry should be applied to all versions of the crate, as it's due to a locally developed crate being also deployed to crates.io or a crates.io crate being vendored locally to perform some modifications.

There is an edge-case when we patch a specific version of a crate to redirect all exports to the more recent version of the crate in order to reduce crate version duplication across our version graph. We don't want to audit the version we're replacing with a redirect, however we do want to audit the target version if we happen to vendor it locally to make changes.

To handle this edge-case, it may be possible to make the value of `audit-as-crates-io` either a bool (as it is today), which would apply to all versions, or potentially a table with entries corresponding to specific versions. If a table is in use, each version in use must be specified explicitly.

**Comment by bholley** [comment]
We realized that since our forwarder crates use fake version numbers (0.7.999), they'll actually never match crates.io and cargo-vet will automatically do the right thing. As such I don't think we have a use-case for this.
