### ISSUE TITLE
audit-as-crates-io breaks dependency computation for affected crates

### ISSUE THREAD

**Issue by bholley** [mozilla/cargo-vet#219]
With the added audit-as-crates-io annotations [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1776096), I get:

> ERROR Panic - A panic occurred at src/resolver.rs:1359: third-party packages shouldn't have dev-deps!

This blocks update cargo-vet in m-c.

**Comment by bholley** [comment]
It also appears that treating first-party crates as third-party is causing us to cull some of the dependencies (optional and dev-dependencies) from the tree that is presumably not waranted.
[diff.txt](https://github.com/mozilla/cargo-vet/files/8962598/diff.txt)

**Comment by bholley** [comment]
STR for the second issue:
(1) apply the patches from https://bugzilla.mozilla.org/show_bug.cgi?id=1776096 to mozilla-central
(2) run cargo vet regenerate-unaudited

**Comment by Gankra** [comment]
this was fixed by #223
