### ISSUE TITLE
Add a --mode to inspect and diff and implement sourcegraph support

### ISSUE THREAD

**Issue by bholley** [mozilla/cargo-vet#245]
Initially supported will be `local` (the current behavior) and `sourcegraph`

For sourcegraph, we should open a browser tab (after acknowledging the interactive part). Inspect should route like [so](https://sourcegraph.com/crates/generic-array@v0.14.5) and diff should route like [so](https://sourcegraph.com/crates/generic-array/-/compare/v0.14.4...v0.14.5).

**Comment by mystor** [comment]
Fixed by #246 and #247
