### ISSUE TITLE
Question: responsibility for auditing crates you own

### ISSUE THREAD

**Issue by eqrion** [mozilla/cargo-vet#265]
If a project/organization is using cargo-vet and publishes a set of crates, are they expected to create audit entries for the crates they publish? Or is it expected that other organizations that use these crates will perform their own audits?

A related variation of this is an organization with multiple repositories, `A`, `B`, `A depending on crates in B`, and an aggregated `supply-chain` repository. In the repo `A` that uses crates from `B`, would it be expected that they have audit entries for `B` that therefore make their way to the `supply-chain` repo?

This might be answered in the book, but I wasn't sure how to piece it together.

**Comment by eqrion** [comment]
> This is definitely a bit of a grey area and in my ideal world no one audits their own stuff (making everything more resilient and peer-reviewed) BUT in a pragmatic world if you trust e.g. mozilla's audits for third-party code, you may as well trust the actual code that mozilla actually develops and publishes, because it's presumably held to an even higher standard.

Yes, I agree with this and I think in practice this is what will happen. So now I'm wondering how this gets organized and stored in metadata.

e.g. If mozilla trusts the bytecodealliance's audits, does mozilla import audit entries from the bytecodealliance that says "we publish this"? Or should the bytecodealliance by convention not have audit entries for their crates, but instead have "*" exemptions for each of their crates, and then mozilla would create audit entries that say "we trust BA"?

I think my preference, in this example, is for the BA to not create it's own audit entries so that people can import their audits while still recording that explicit trust edge for themselves. And I think when aggregating across repos, that would require them to use exemptions for their own crates?

**Comment by bholley** [comment]
I think we should add an FAQ entry about this, so morphing the issue to be about that.

**Comment by bholley** [comment]
This is now described [here](https://mozilla.github.io/cargo-vet/curating-your-audit-set.html#self-certification).
