### ISSUE TITLE
policy.audit-as-crates-io errors mask other errors

### ISSUE THREAD

**Issue by glandium** [mozilla/cargo-vet#288]
Currently, on mozilla-central, if you run `mach cargo vet`, you get the following error:
```
ERROR 
  × There are some issues with your policy.audit-as-crates-io entries

Error: 
  × Some non-crates.io-fetched packages match published crates.io versions
  │   viaduct:0.1.0
  help: Add a `policy.*.audit-as-crates-io` entry for them

```

If you also have _other_ errors, they don't appear. So when you run `mach vendor rust`, it doesn't find any vet error relevant to vendoring, and goes through, even when such errors do exist. Running `mach cargo vet --locked` under those conditions _does_ prevent the policy.audit-as-crates-io from showing up and display the other errors (which phabricator CI catches because it uses `--locked`)

**Comment by glandium** [comment]
Relatedly, the json version of the policy.audit-as-crates-io error doesn't expose the involved crate name in a convenient way.

**Comment by bholley** [comment]
I'm a little confused. Is the idea that these aren't being reported as errors, or that `mach cargo vet` is filtering a subset of error categories?

**Comment by bholley** [comment]
Basically I agree that `./mach vendor rust` should definitely fail if cargo-vet has failures, but it would naively seem acceptable to surface only the most immediate error (the audit-as-crates-io) first and then surface subsequent errors once those issues are resolved.

**Comment by glandium** [comment]
I'm not convinced that the policy.audit-as-crates-io error should be the first to be presented.

**Comment by glandium** [comment]
Especially when it's an error that will be silenced by `--locked`.

**Comment by glandium** [comment]
Also interestingly... in this case, what happened is that a new crate with the same name as one we have in m-c was uploaded to crates.io 4 days ago...

**Comment by mystor** [comment]
I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1786062 to make `./mach vendor rust` actively report all errors, rather than only reporting vet failures, so it can catch things like `audit-as-crates-io` failures, import criteria changes, networking errors, or violation conflicts which were previously being ignored.

**Comment by mystor** [comment]
Given that https://bugzilla.mozilla.org/show_bug.cgi?id=1786062 has landed, I think this issue can probably be closed unless there's another issue. We'll also report issues like violation conflicts first before showing audit errors even if the violation conflict is from a live import and therefore would generally be silenced by `--locked`, and I don't know if it necessarily makes sense to delay them, given that the response to these errors does impact how the resolver is run and what errors/audits should be performed.
