### ISSUE TITLE
RFC: Wildcard Audits

### ISSUE THREAD

**Issue by bholley** [mozilla/cargo-vet#353]
When an organization publishes its own code as a third-party crate and then consumes it back into the main project, cargo-vet allows [self-certification](https://mozilla.github.io/cargo-vet/curating-your-audit-set.html#self-certification). In practice this seems to be a [common](https://searchfox.org/mozilla-central/rev/2f47e3dacf0d773e9c7f363cecf10cfbea490679/supply-chain/audits.toml#513) [pattern](https://github.com/bytecodealliance/wasmtime/blob/3b6544dc66e704a185d7aaf8cc50bcad9d7c7f75/supply-chain/audits.toml#L606) for organizations today.

The current workflow for this is a little clunky:
* The author needs to touch audits.toml each time they go through a publishing cycle, which may require [explicit approval](https://groups.google.com/a/mozilla.org/g/governance/c/wMWBqkCnR34).
* If there's any delay between publishing the new version and pulling it into the main project, other consumers may find themselves importing it before the self-certification is available and end up [reauditing](https://phabricator.services.mozilla.com/D161748#change-fIGTpIsXGUmk).
* The certify UX isn't really optimized for the self-certification case.
* It feels like busywork, and pollutes the audit log with a bunch of repetitive and low-signal information.

We have thus far intentionally avoided a "just trust this crate" feature because there are lots of ways it could go wrong. However, I think I've come up with a set of guardrails that strike the right balance between ergonomics and security.

The feature would enable entries like this to `audits.toml`:

```
[[wildcards.wast]]
who = "Alex Crichton <alex@alexcrichton.com>"
criteria = "safe-to-deploy"
user-id = 1
start = "2019-10-1"
end = "2023-11-1"
notes = "The Bytecode Alliance is the author of this crate and ensures that all published versions are safe-to-deploy."
``` 

A few things to note:
* Like other content in `audits.toml`, these entries would be shareable by default, though we could provide a mechanism to ignore them when specifying the import. This is important to preserve the dynamic wherein small developers can piggy-back on the legwork of well-known organizations in figuring out what's safe.
* We restrict the wildcard to a single publisher, who should generally be the person on the "who" field. The idea is that this person is saying "any version of this package I publish in this date range will meet the provided criteria".
* We identify the publisher by crates.io user-id, rather than GitHub handle, because people can rename their GitHub handle and the old handle becomes available if they don't remember to squat it. We can maybe add some sugar for looking up your user ID in the `certify` workflow.
* We bound the wildcard by a publish date range, rather than a version range.
* We restrict the end date to 1 year into the future. This requires people to periodically renew their wildcards and avoids an indefinite blank check in cases where people drift away from the project.
* If a wildcard is needed in the vetting algorithm, it's reified into `imports.lock` to enable operation in `--locked` mode.
* API call results are cached in the cache directory, and only refetched if the registry index shows a new publish for the relevant crate (or the cache is cleared).

**Comment by bholley** [comment]
CC @alexcrichton @jameysharp @chutten @badboy @jgraham @eqrion @jimblandy

**Comment by alexcrichton** [comment]
If the issue here is around the `wasm-tools` family of crates specifically, the main reason that is sort of clunky right now is that the audits are in the wasmtime repository so we don't get around to auditing them until we update in Wasmtime, which is often delayed from the publication in the wasm-tools repository itself. That can be solved by having a separate audit list over in that repository plus some modifications to our publication scripts to add relevant entries to the audit log as well.

If there are other motivations for this feature then it seems reasonble to me, although I don't have too too much of an opinion personally. Mostly just wanted to point out that the `wast`-specific case, if that's the main motivator for this, I think is reasonable to solve via preexisting means. (although I'm sure there's still UX improvements for that route as well)

**Comment by bholley** [comment]
That's an interesting point. I think the general description of that pre-existing mechanism is that you'd record the audits for the sub-project in the sub-project's repo, and set up `cargo vet aggregate` to pull from each of those repos.

I think that kinda works, but is still a little bit clunky:
* You still have to deal with adding an explicit audit at publish time, just in a different place. This requires setting up such a process and educating the maintainers on that process.
* The obvious way to set this up would be to enable cargo-vet for the sub-project, but managing that instance comes with some overhead you might not want if you weren't otherwise using cargo-vet there.
* This would allow the maintainers of the sub-project to inject arbitrary audits into the set, rather than just audits for that sub-project, which is broader than needed.

So I think the wildcard thing is still an improvement.

**Comment by repi** [comment]
I like this proposal! 

We are gradually adding all of our published crates as self-certified for our organization and store them in a public repository for other projects to see ([`audits.toml`](https://github.com/EmbarkStudios/rust-ecosystem/blob/main/audits.toml)). 

And we do have quite a few public crates that developers in our org are releasing, [73 at least count](https://crates.io/users/embark-studios), and while right now it has been mostly me updating the audit versions I would like to distribute this in the team as different devs own and release different projects but it does indeed feel like busywork and error prone for everyone to update a single central file for every version update of every project. 

So the idea of having a auto-self-certify with a time range would be a much cleaner solution where devs in our org would only have to add new projects to it and, say every 6-12 months update the expiry date of the audit.

Would the user-id be the crates.io user-name? We for example publish all of our crates from our [`embark-studios`](https://crates.io/users/embark-studios) user so it would be `user-id = "embark-studios"`, or is there some additional numeric crates.io user id?
