### ISSUE TITLE
Extra newlines at the end of TOML files

### ISSUE THREAD

**Issue by divergentdave** [mozilla/cargo-vet#390]
Starting with `cargo-vet` 0.3.1, the various TOML files all have an extra newline at the end of the file. `git diff-index --check --cached` reports this as a "whitespace error", saying `supply-chain/audits.toml:137: new blank line at EOF.` If it wouldn't be too much trouble, it'd be nice to drop the extra newline.

**Comment by mystor** [comment]
This has been already fixed as part of #348, which will be in 0.4.0 when that is released.

**Comment by divergentdave** [comment]
Sounds good, thanks!
