### ISSUE TITLE
Avoid importing self audits when pulling from an aggregated source

### ISSUE THREAD

**Issue by bholley** [mozilla/cargo-vet#400]
I now have aggregate running for Mozilla here: https://github.com/mozilla/supply-chain

However, when I add that as an import for Firefox, I get an enormous dump of all the audits we already have in Firefox. Ideally we would not have that duplication.

@mystor Is this problem just going to go away with the other work we have planned to be more minimal about what we import?

**Comment by bholley** [comment]
I just tried this on top of the changes in #399 and the problem does indeed go away. \o/

**Comment by mystor** [comment]
Yes, as you noted this will be going away with the changes in #399 as we will be only importing the audits which are used.
