### ISSUE TITLE
Document wildcard audits in the book

### ISSUE THREAD

**Issue by mystor** [mozilla/cargo-vet#403]
Wildcard audits (#353) are being implemented in #398, but have not yet been documented in the book. Once that patch lands, we should update our documentation in the book and elsewhere to also mention and explain this type of audit.

The book should also cover the new certify ux which we'll add in #402.

**Comment by mystor** [comment]
Added some new docs in #421 - @bholley do you think that'll be enough for 0.4?

**Comment by bholley** [comment]
I added #424 to make a few fixes, can close this with that.
