### ISSUE TITLE
Exhaustivity requirements for versioned policy entries are too broad

### ISSUE THREAD

**Issue by bholley** [mozilla/cargo-vet#404]
I just tried pulling the latest cargo-vet into m-c. We have two versions of mio, one of which is a local fork of 0.6.3 and another of which is a regular upstream 0.8.0. We have a policy entry for 0.6.3 to set audit-as-crates-io=true.

The new cargo-vet wants me to version the 0.6.3 policy entry, which makes sense. However it also wants me to add a policy entry for 0.8.0, which makes less sense. Is it supposed to be an empty policy entry? Am I supposed to specify audit-as-crates-io, and if so, what would it even mean in the context of a third-party crate?

The behavior we're seeing matches the [originally-proposed design](https://github.com/mozilla/cargo-vet/issues/379#issue-1550002405), we just didn't think this aspect through. I do think the behavior I described above is pretty confusing and that we should address it somehow.

**Comment by mystor** [comment]
This was fixed in #406
