### ISSUE TITLE
Avoid removing unnecessary imports and exemptions unless explicitly requested

### ISSUE THREAD

**Issue by mystor** [mozilla/cargo-vet#411]
After a discussion with wasmtime, it seems that the minimal imports approach from #399 of always using the absolute minimum possible set of imports may not be the best approach going forward. Instead, we want to try a hybrid approach which only imports the minimum set of new audits, but which also keeps any existing imports around until they're explicitly cleaned up by a command.

We could then emit a warning when running a command like `cargo vet` or `cargo vet suggest` directing the user to run a command to clean up unnecessary imports and exemptions, without performing unexpected changes when running normal vetting & certifying commands. One of the advantages of this is it allows workflows when interacting with external contributors where a core contributor can pre-vet/exempt a new crate or a new version of a crate for a contributor, and land the changes to the store before the contributor's patch lands without breaking the build.

This builds on top of the ideas from #391 by extending the logic to also apply to removing imports and exemptions which are no longer used, even by local commands. We will still want to have an option to perform exemption minimization for a single crate, potentially pulling in new imports, when `cargo vet certify` is run.

The current idea is to introduce a new command, `cargo vet prune`, which attempts to prune both exemptions and imports, with command line options to configure the behaviour. This may be able to replace the existing `cargo vet fetch-imports` (and potentially `cargo vet regenerate imports`) command(s).

**Comment by bholley** [comment]
FYI @alexcrichton @jameysharp @fitzgen @cfallin the above is what we're looking to do, which seems preferable to a configuration knob.
