### ISSUE TITLE
Certifying a wildcard audit doesn't activate it until `vet check` is run again

### ISSUE THREAD

**Issue by bholley** [mozilla/cargo-vet#419]
@chutten pointed this out. For a non-wildcard certify, the audit is immediately applicable whether or not you run check again, because it's directly recorded in `audits.toml`. But for wildcard audits, it's not valid without the publisher details in `imports.lock`.

It seems like we kind of want an implicit `vet check` after wildcard certification, though I'm not sure if we'd run into trickiness in the case that vet still fails.

@mystor WDYT?

**Comment by mystor** [comment]
We actually do an implicit `vet check` for specifically the package which was certified during `cargo vet certify`

https://github.com/mozilla/cargo-vet/blob/4a0185658b989ea43c1a495f20c1ff7ff8d7ed58/src/main.rs#L1066-L1078

Unfortunately it looks like I made a mistake when doing this as we don't call this method on the wildcard audit codepath. If we change that around it should work properly.
