### ISSUE TITLE
Strange internal failures

### ISSUE THREAD

**Issue by hpenne** [mozilla/cargo-vet#422]
I'm a little stuck due to some errors with cargo vet. I've changed the dependencies a bit and "cargo vet check --locked" now outputs a "Vetting failed" (which was expected) followed by "5 unchecked dependencies:".

And then nothing.  It does not output the names of the crates it considers unchecked, which it used to do when everything was working.  No error message, either.

If I run "regenerate exemptions" to try to figure out the unchecked crates that way, then it stops on a panic in resolver.rs 3473:13 ("failed to make progress while allowing new exemptions?").

This is on version 0.3.  Is this a known problem?  Are there any workarounds that I could try?

**Comment by hpenne** [comment]
The problem is also present on versjon 0.3.1. The resolver.rs module seems to have gone through a major rewrite since then. Are there any new releases planned that might fix this?

**Comment by bholley** [comment]
@hpenne Yes, we're probably a few days away from a big 0.4 release. For now, can you pull it down from git and give it a try to see if your issue is fixed?

**Comment by hpenne** [comment]
We have build cargo vet from the source of the main branch.  "check" now correctly outputs the unchecked dependencies.  That's good.

"regenerate exemptions" does not panic, but it removes about half of our exemptions and "check" fails after that.  I did not expect that.  I seem to remember that the setup changes a bit relative to 0.3.0.  We have not checked if any of our files need changes, but I would not expect this behaviour regardless.  I intuitively expected "regenerate exemptions" to make "check" pass (although I haven't given it much serious though).  It looks a little like a bug of some sort.

**Comment by bholley** [comment]
> We have build cargo vet from the source of the main branch. "check" now correctly outputs the unchecked dependencies. That's good.

Great.
 
> "regenerate exemptions" does not panic, but it removes about half of our exemptions, and all of the imports, and "check" fails after that. I did not expect that. I seem to remember that the setup changes a bit relative to 0.3.0. We have not checked if any of our files need changes, but I would not expect this behaviour regardless. I intuitively expected "regenerate exemptions" to make "check" pass (although I haven't given it much serious though). It looks a little like a bug of some sort.

Interesting, that does sound like a bug in `regenerate exemptions`. If you're able to create a reduced testcase (or privately share a redacted copy of your project with us), @mystor can take a look.

**Comment by hpenne** [comment]
That might take a while to produce, but I'll see what I can do. How "real" does a source tree need to be for cargo-vet to work? Is a cargo.toml and cargo.lock sufficient?

**Comment by bholley** [comment]
I believe that's correct. You should be able to delete all your actual source code, just the cargo metadata should be sufficient.

**Comment by mystor** [comment]
> "regenerate exemptions" does not panic, but it removes about half of our exemptions, and all of the imports, and "check" fails after that. I did not expect that. I seem to remember that the setup changes a bit relative to 0.3.0. We have not checked if any of our files need changes, but I would not expect this behaviour regardless. I intuitively expected "regenerate exemptions" to make "check" pass (although I haven't given it much serious though). It looks a little like a bug of some sort.

Yes, `regenerate exemptions` removing a bunch of exemptions and imports is expected (since 0.3.0 we are now much more precise about which imports/exemptions we actually depend upon), but `check` should definitely be passing after that point, unless there are violations (which would be communicated in the error produced by `cargo vet check`).

Earlier you mentioned you were running `cargo vet --locked` - are you running `cargo vet regenerate exemptions --locked` as well? I think that ought to still somewhat work off the top of my head (won't pull in new imports naturally), but it's certainly a less tested configuration.

**Comment by hpenne** [comment]
Some observations when running cargo-vet built from the latest source:

Running "cargo vet regenerate imports" deletes all entries in the imports.lock file. All that is left is a single line containing "[audits.mozilla.audits]".  That seems wrong and is completely fatal.
The command outputs a warning (and nothing else) to the console: "WARN Couldn't find cargo registry: reference 'refs/heads/master' not found; class=Rerefence(4); code=NotFound (-3)".

Running "cargo vet regenerate imports" also deletes a large number of exemptions from "config.toml".  That also seems wrong.  I would expect this command to regenerate imports, not exemptions.

Running "cargo vet check --locked" after that (obviously) generates output about missing audits.  What is strange is that the the audit type is missing:
"  my-crate:X.Y.Z missing []"
I would expect to see either "safe-to-run" or "safe-to-deploy" at the end.  I do have some high level dependencies configured with [] as audit-criteria, but that does not affect most of these crates and cannot explain why this happens.

Removing this makes cargo-vet correctly state the required audit criteria, so it seems like use of this criteria mapping breaks cargo-vet.  The tool will not be usable to us if it is released with out a fix for this.

Reverting everything and running "cargo vet regenerate exemptions --locked" has the following effect (no warning on the console):
1) Cleans out all the imports (just like "regenerate imports" did).
2) Deletes all exemptions.

**Comment by hpenne** [comment]
I have experimented with removing stuff from my config.toml to see if that makes cargo-vet more well behaved.  I found something interesting.

I have the following in config.toml:
`
[[imports.mozilla.criteria-map]]
ours = "safe-to-run"
theirs = "safe-to-deploy"
`

If I remove that block (and nothing else) then things start to behave much better.  "cargo vet regenerate imports" removes a lot of imports, but leaves the ones that are necessary. It leaves the exemptions alone, and "cargo vet check --locked" still succeeds.  "cargo vet regenerate exemptions --locked" also behaves as expected.

So it seems that the use of the criteria mapping breaks cargo-vet.  My guess is that this should be reasonably easy to reproduce at your end.  This is a critical bug to us, and I really hope that you can fix this before you release.

Btw., the warning I mentioned seems to appear only when I leave out "--locked" from the command.

**Comment by mystor** [comment]
> If I remove that block (and nothing else) then things start to behave much better. "cargo vet regenerate imports" removes a lot of imports, but leaves the ones that are necessary. It leaves the exemptions alone, and "cargo vet check --locked" still succeeds. "cargo vet regenerate exemptions --locked" also behaves as expected.

Oh interesting - remapping the built-in criteria is definitely something which we haven't supported at all right now. We always map every default criteria to itself, and only support remapping other criteria. I suppose there's definitely a possibility that this would cause some super weird behaviour if we both have a mapping on the default criteria and the implicit direct mapping. 

I imagine that you'd expect this mapping to override the default mapping behaviour of the built-in criteria to themselves when importing from a peer?

**Comment by hpenne** [comment]
> Oh interesting - remapping the built-in criteria is definitely something which we haven't supported at all right now. We always map every default criteria to itself, and only support remapping other criteria. I suppose there's definitely a possibility that this would cause some super weird behaviour if we both have a mapping on the default criteria and the implicit direct mapping.
> 
> I imagine that you'd expect this mapping to override the default mapping behaviour of the built-in criteria to themselves when importing from a peer?

Just to make sure I'm not misunderstanding what you write: The purpose of this block in our setup is to "demote" the imported "safe-to-deploy" audits to "safe-to-run" because the policy is that we can only trust our own audits for "safe-to-deploy".  

Unless I read it wrong (which is always a possibility), section 3.1 of the docs says that this is the way this should work in 0.3.0, and it seemed to work in that version.  From outside, this looks like a regression.

I'm not sure what your processing looks like, but If this mapping is done on import of the audits then it should not affect the rest of the processing.  This behaviour is essensial to us.  Can this be fixed for 0.4.0?

**Comment by hpenne** [comment]
> It may or may not be easy to support this kind of remapping of the built-in criteria (will let @mystor speak to that). If we decide we don't want to support it, we should at least error-out when it's specified.

@bholley Agreed, it should either work or error.  Futhermore, the documentation needs to clearly state this limitation.

> @hpenne I think an alternative approach to what you're trying to do is to define your own custom version of safe-to-deploy, and require that (using policy entries) for all the crates in your project. This is what [ChromeOS does](https://chromium.googlesource.com/chromiumos/third_party/rust_crates/+/main/cargo-vet/audits.toml#23). Would that work for your use-case?

@bholley That may be acceptable if this can be set up using the single "default-criteria" top level key in config.toml.  If I have to specify a custom criteria on all our top level crates, then no.  But that is a workaround (as the need to error out and to add information about limitations to the docs illustrate). The logical solution is to make the import mapping work as advertised.  If the mapping is done on import then this should (hopefully) be an easy thing to fix.

Overall, I think this is a great tool.

**Comment by hpenne** [comment]
@bholley I tried your suggestion on a project at work this morning.  "default-criteria" was not the answer (as you probably already knew), but defining a new criteria type and applying that to the a top level application works.  I only need apply it to the top and it propagates nicely down the dependency tree.  That will work well for us.  In fact, I see some advantages to this technique for a use case that we will probably need to look into soon.  So thank you for the tip.  It seems that we can live with the current behaviour (0.4.0) of criteria-map, although I still find it a bit counter intuitive.

@mystor I had a very brief look at the source code for cargo-vet as well.  I did not have much time and could only give it a brief glance, but I would still like to retract my suggestion that it might be easy to fix the criteria-map oddity that I found.  It seems that CriteriaMap is used in a lot of places, and probably not just in the import phase.  Since I don't know the inner workings of cargo-vet it would seem (because I don't know any better yet) that it might be possible to apply the mapping to the import stage only (and record the mapped criteria types in imports.lock) and simplify the following logic because the mapping is already taken care of, but reality is seldom as simple as a brief first glance will suggest.  I suspect that you will immediately know if this is good idea or not.

**Comment by mystor** [comment]
> "default-criteria" was not the answer (as you probably already knew), but defining a new criteria type and applying that to the a top level application works.

Yeah, we don't have support for `"default-criteria"` yet, it is being proposed in #408.

> Since I don't know the inner workings of cargo-vet it would seem (because I don't know any better yet) that it might be possible to apply the mapping to the import stage only (and record the mapped criteria types in imports.lock) and simplify the following logic because the mapping is already taken care of, but reality is seldom as simple as a brief first glance will suggest. I suspect that you will immediately know if this is good idea or not.

Criteria mapping currently happens quite late during the resolver because of the (now-removed) support for dependency-criteria on audit entries, which would mean that an audit for an imported criteria could actually end up depending on a different audit for a non-imported criteria from a foreign namespace. This meant that we couldn't do straightforward remapping of criteria at import time.

With the current limitation of 1:1 mapping of criteria into the local namespace, it may be possible to do some amount of simplification here to perform this sort of mapping at import time as you mention. This does have the potential for some slight weirdness due to the interactions between remote and local implies relationships, but it is something which I have considered doing. I just haven't gotten around to since the recent dependency-criteria removal.

All of this wouldn't be required to support re-mapping the built-in criteria, but it'd still be something which we'd need to figure out the desired semantics for, especially in cases like remapping `safe-to-run` to `my-safe-to-deploy` or similar.

**Comment by mystor** [comment]
I've filed #425 to investigate supporting remapping built-in criteria when importing in the future, and made #426 to emit an error when trying to remap built-in criteria, rather than creating an implies cycle and breaking silently.

**Comment by hpenne** [comment]
> Criteria mapping currently happens quite late during the resolver because of the (now-removed) support for dependency-criteria on audit entries, which would mean that an audit for an imported criteria could actually end up depending on a different audit for a non-imported criteria from a foreign namespace. This meant that we couldn't do straightforward remapping of criteria at import time.

Yes, that sounds complicated, indeed.

> With the current limitation of 1:1 mapping of criteria into the local namespace, it may be possible to do some amount of simplification here to perform this sort of mapping at import time as you mention. This does have the potential for some slight weirdness due to the interactions between remote and local implies relationships, but it is something which I have considered doing. I just haven't gotten around to since the recent dependency-criteria removal.

I'm not familiar with the concept of remote implies relationships. My guess would be this is implies relationships defined on custom audit criteria defined remotely by someone that I import audits from.  The docs section 2.4 seems to say that remote audit criteria need to be mapped to local ones, so it seems to me that remote implies relationships do not get imported at all, and would not be an issue. Perhaps I misunderstand, or you have things in the backlog that relate to this.  Generally, remote implies relationships is something that I would not want to affect us at all.  I would prefer to map remote custom audit criteria explicitly to local ones, to have full control of this locally.  If so, then perhaps this is not so much of an issue.

> All of this wouldn't be required to support re-mapping the built-in criteria, but it'd still be something which we'd need to figure out the desired semantics for, especially in cases like remapping `safe-to-run` to `my-safe-to-deploy` or similar.

Personally, I would find it logical if this just set "my-safe-to-deploy" on imported audits that were "safe-to-run" (during import).

Our setup no longer requires this, though. I've added a custom criteria above "safe-to-run" that we use for the cases where imported "safe-to-deply" is not considered trustworthy enough, which removes the need to remap audit criteria for imports. That turned out to be more logical setup that allows more fine grained control and better fits the problem that we need to solve.

**Comment by bholley** [comment]
Just a note on remote implies — this is a feature we want to keep working to support use cases like [this one in ChromeOS](https://chromium.googlesource.com/chromiumos/third_party/rust_crates/+/main/cargo-vet/audits.toml#51). The basic idea there is that they have a slightly stricter version of safe-to-deploy which they want to enforce internally, but also want to make their audits available to the rest of the world as regular safe-to-deploy audits without everybody needing to worry about understanding and mapping them. Beyond the convenience and simplicity factors, automatic mapping is also important to enable [registry suggestions](https://mozilla.github.io/cargo-vet/performing-audits.html#suggestions-from-the-registry) (which we haven't implemented yet but plan to).

**Comment by bholley** [comment]
We added an error in #426.
