### ISSUE TITLE
Prompt the exact `cargo vet certify` command after `cargo vet diff`

### ISSUE THREAD

**Issue by afranchuk** [mozilla/cargo-vet#454]
When a user runs `cargo vet diff ...`, after launching the diff it prompts the user to run `cargo vet certify`, but it doesn't provide the arguments that should be used (related to the diff). While it is very simple (just replace `diff` with `certify`), it would be nice to be explicit about the certify command to run.

**Comment by bholley** [comment]
The idea is that it's supposed to just remember the last diff/inspect, so you can bareword invoke `cargo vet certify`. Is that not happening in your case, or was the existence of that magic just unclear?

**Comment by afranchuk** [comment]
Ah! The magic was unclear (though perhaps if I read the tutorial-focused documentation more thoroughly that would have been obvious).
