### ISSUE TITLE
Avoid audit-as-crates-io errors when upstream publishes a new version

### ISSUE THREAD

**Issue by bholley** [mozilla/cargo-vet#464]
Over in Firefox, we recently encountered a bit of a [hiccup](https://bugzilla.mozilla.org/show_bug.cgi?id=1830488) with audit-as-crates-io.

The basic pathology was as follows:
1. Originally we were using [cssparser](https://crates.io/crates/cssparser) as an upstream crate.
2. We switched it to a git override to pull in some unreleased upstream changes, which included a version bump to 0.31.0
3. 0.31.0 was released upstream.
4. `cargo vet` started breaking with `Some non-crates.io-fetched packages match published crates.io versions`, and users are confused.

The source of confusion here is that the user implementing step (2) is different from the user encountering the error in step (4), and the problem can be precipitated at arbitrary times but another (potentially-unaffiliated) individual performing an out-of-band crates.io change in step (3). The ideal behavior is for the `audit-as-crates-io` entry to be required at step (2).

The underlying issue is that our criterion for "does this package need an audit-as-crates-io entry" is based on matching local versions with published versions, which is vulnerable to this exact kind of off-by-one failure mode.

I propose that we switch the "do you need an audit-as-crates-io entry" check from a version match to a description (or, if available, repository url) match. We already started using these fields in #441 to guess the correct audit-as-crates-io value during init/regenerate, but here I'm suggesting that we _assume_ that two same-name crates which share neither a description nor a repository URL across any published versions are unrelated to each other. This has the added benefit of reducing the number of audit-as-crates-io entries many projects will need [1].

We then need to deal with the fact that we'll now be permitting audits for versions of crates that don't exist on crates.io. For git dependencies, we now have an easy way to represent these with the `@git` syntax. For path dependencies, it's trickier — I think for now we can just require the user to rectifying the situation by requiring the user to either make the local version number match a published version (presumably the most-recently-published version), or set `audit-as-crates-io = false`.

[1] Aside from being a better similarity indicator, there's also a structural advantage: many local crates in Firefox have no description, whereas crates.io _requires_ a description for publication.

**Comment by bholley** [comment]
@mystor @afranchuk WDYT?

**Comment by afranchuk** [comment]
This sounds reasonable to me. It's a tricky problem for sure, but since we've recently started to use the description as a fuzzy heuristic to match up crates, I think it's fine (and maybe more predictable/consistent) to do so in this case as well.
