### ISSUE TITLE
Introduce nagging mechanism to update wildcard audit expiration

### ISSUE THREAD

**Issue by bholley** [mozilla/cargo-vet#465]
Wildcard audits have an expiration date (which can be at most one year in the future) so that the supply-chain owners will need to periodically reevaluate their relationship with the publisher and ensure the individual still carries the organization's stamp of approval. The rough expectation is that wildcard audits from individuals who are no longer associated with the project should be allowed to expire, though "associated" is a fuzzy concept and therefore some discretion is inevitable.

There are now dozens of wildcard audits in the ecosystem, all of which expire roughly one year after the feature was introduced. When that time comes around, most of them would ideally be renewed by bumping the `end` date. However, there's not a general mechanism to prompt people to do so. This could result in annoyance wherein project A depends on an imported wildcard audit from project B, but the person in project B hasn't bumped the expiration yet (perhaps because they're no longer using the crate within the project).

My proposal is to add a nag — similar to the `prune` nag — for any local wildcard audits that are expiring within the next six weeks:

```
WARN: Your audit set contains wildcard audits for foo, bar, and baz which expire within the next six weeks.
WARN:   Consider running `cargo vet renew --expiring` or adding `suggest-renewal = false` in audits.toml.
```

We'd then introduce the `cargo vet renew` command, which takes either an explicit crate name or the `--expiring` flag which operates on all wildcard audits expiring within the next six weeks.

**Comment by afranchuk** [comment]
Do we want `cargo vet renew` to also support setting the amount of time to consider for `--expiring` (e.g. `cargo vet renew --expiring "1 week"`)?

**Comment by afranchuk** [comment]
The proposed `renew <crate>` command is somewhat loose, as individual wildcard audits are actually addressed by crate name and user id. I'm not sure whether we want to (optionally) allow specification of a user id as well.

**Comment by bholley** [comment]
I think just `renew CRATE` and `renew --expiring` should be enough. If there's an expiring audit that you don't want to renew (which I suspect is the exception rather than the rule), you can set `suggest-renewal = false`, use explicit renewal, or just drop that part of the diff with git.
