### ISSUE TITLE
Audit-as-crates-io detection needs some work

### ISSUE THREAD

**Issue by bholley** [mozilla/cargo-vet#472]
There are a few problems in the wake of #469 that I think we shouldn't ship:
* On big projects like Firefox and wasmtime, there's about a 1-minute spinnerless hang while cargo-vet hits the rate-limited crates.io API for all the first-party crates to see if there's a name collision. These results are cached, but only for 24 hours.
* The current flow leads users to set audit-as-crates-io=true for path crates with non-published versions, which is both semantically unsound and leads to problems elsewhere in the tool.

I think what we want is:
* Require public versions for path dependencies with audit-as-crates-io=true
* * Default to audit-as-crates-io=false when there's not a public version (at least during `init`, so that it always succeeds).
* Faster ability to quickly check whether there's a name collision by first hitting the non-rate-limited CDN, and only doing API lookups for crates that get a hit on the index.

**Comment by afranchuk** [comment]
> Faster ability to quickly check whether there's a name collision by first hitting the non-rate-limited CDN, and only doing API lookups for crates that get a hit on the index.

Why use the network at all? Do we want to phase out using/updating the local index? If so that's fine, a `HEAD` request for each package will be quick and the resulting yes/no can be cached (in the case of "yes", probably indefinitely).

**Comment by bholley** [comment]
My thinking was that `cargo metadata` only pulls the index if there are missing crates in the graph, and so to reliably use the index for existence checking we'd need to hook into it at a lower level which feels a little complicated and risky.

**Comment by afranchuk** [comment]
I suspected as much, but wanted to confirm. This doesn't mention adding the spinner but I'll take that as another bullet point :)
