### ISSUE TITLE
Support for sparse indexes/registries

### ISSUE THREAD

**Issue by mikhasd** [mozilla/cargo-vet#475]
My company vendors all 3rd party packages/crates to an internal registry which implements the `sparse` protocol.

When running `cargo vet` I get the following error:
` WARN Couldn't find cargo registry: 'sparse+https://INTERNAL/INDEX/' is not a valid registry url`

I have noticed that the latest cargo-vet@v0.6.1 uses crates-index@v0.18.8, but sparse index support was only implemented on v0.19.7.

I'm not sure if this is the only required change though.

**Comment by mystor** [comment]
We no longer attempt to look at your local registry at all since #496

**Comment by mikhasd** [comment]
Thanks @mystor.
What is the behaviour of cargo-vet in case I don't have access to crates.io (blocked by firewall)?

**Comment by bholley** [comment]
> Thanks @mystor. What is the behaviour of cargo-vet in case I don't have access to crates.io (blocked by firewall)?

`cargo vet --locked --frozen` will work without hitting the network to verify an existing tree (for use in situations like CI). In general though, the expectation is that ordinary invocations on the developer's machine can access crates.io.
