### ISSUE TITLE
Publish pre-built binaries of cargo-vet

### ISSUE THREAD

**Issue by repi** [mozilla/cargo-vet#484]
While this tool is still in development, I do feel it and the ecosystem has matured quite a bit and would love to easily run it in CI in multiple of our repositories now. 

One can do it with building & caching it as suggested in the [docs](https://mozilla.github.io/cargo-vet/configuring-ci.html), but it would be much more preferable to have pre-built binaries published for main linux/windows/mac targets (esp. linux) directly in the releases here (for example like [cargo-deny](https://github.com/EmbarkStudios/cargo-deny/releases/tag/0.13.9) or [scache](https://github.com/mozilla/sccache/releases/tag/v0.5.0) does it). Would be faster CI and easier to integrate in solutions that do not have caching.

Would this be possible to setup? One can take inspiration from some existing repos (like mentioned above) of how they build and publish it through github actions.

**Comment by bholley** [comment]
Would be happy to take a patch for this.

**Comment by repi** [comment]
this could be very good use case for the new [`cargo-dist`](https://github.com/axodotdev/cargo-dist) to set up release workflow and deployment of binaries and try it out (and give feedback to @axodotdev about it).

maybe something @Gankra at axo would be interested in as another real test project to use it on?

**Comment by staktrace** [comment]
I have a PR up at https://github.com/mozilla/cargo-vet/pull/600 that sets up the `cargo-dist` release workflow. It was pretty painless, kudos @Gankra (and team) for that.

For context, we'd like prebuilt binaries published so that we can use them via the [hermit](https://github.com/cashapp/hermit) tool.
