### ISSUE TITLE
cargo vet trust --all papercuts

### ISSUE THREAD

**Issue by bholley** [mozilla/cargo-vet#499]
Two papercuts I've discovered:

(1) It only seems to work on crates for which you have exemptions, but not for crates which are actively failing to vet. This seems like an oversight and not what we want.

(2) The "skipping X because it has multiple authors" can be kind of annoying. I think we should add a `--force` to override it.

**Comment by repi** [comment]
1) ah that explains some issues with it not working that I've been running into as well

2) agreed! this is a bit annoying and having to type of each individual crate instead, `--force` would be nice!
