### ISSUE TITLE
Calling source graph with `?visible=1000000` ends in 500

### ISSUE THREAD

**Issue by cemoktra** [mozilla/cargo-vet#578]
Using `?visible=1000000` causes 500 on sourcegraph.com, e.g.:

https://sourcegraph.com/crates/openapiv3/-/compare/v1.0.2...v1.0.3?visible=1000000

![image](https://github.com/mozilla/cargo-vet/assets/15634263/467341f4-03a9-4ae3-9dff-470e32774e3f)

vs 
https://sourcegraph.com/crates/openapiv3/-/compare/v1.0.2...v1.0.3

![image](https://github.com/mozilla/cargo-vet/assets/15634263/468b90ee-5a23-4f1c-b54f-f31d0c5e1f5d)

**Comment by cemoktra** [comment]
This specifically relates to https://github.com/search?q=repo%3Amozilla%2Fcargo-vet%201000000&type=code

I dont know why that changed on sourcegraph, but either removing that number completely or reducing it should help

**Comment by cemoktra** [comment]
7000 works, 7500 no

**Comment by jdorfman** [comment]
Thanks @cemoktra looking into it.

**Comment by cemoktra** [comment]
This now ends in 400 but still not working

**Comment by jdorfman** [comment]
@cemoktra @bholley unfortunately, we had to put the `visible` limit back. Bots have been abusing the `?visible=1000000` query string which drove up costs and slowed the service down for others.

**Comment by cemoktra** [comment]
@jdorfman can you tell the limit? I can prepare an according MR then

**Comment by jdorfman** [comment]
@cemoktra 5 e.g. `https://sourcegraph.com/crates/openapiv3/-/compare/v1.0.2...v1.0.3?visible=5`

**Comment by cemoktra** [comment]
No I mean the maximum.
