### ISSUE TITLE
Make a new release with the importable field

### ISSUE THREAD

**Issue by ohaponiuk** [mozilla/cargo-vet#585]
Hi, not exactly an issue but we're using Mozilla's supply chain ([this one](https://hg.mozilla.org/mozilla-central/raw-file/tip/supply-chain/audits.toml)) as a source for our own supply chain and in there an `importable` field is being used. The latest cargo-vet version (0.8.0) was released just before [this PR](https://github.com/mozilla/cargo-vet/pull/520) was merged, so it looks like you compile it yourself for your supply chain or is there an experimental version somewhere present? Thanks in advance.

**Comment by bholley** [comment]
Thanks for the poke. I've gone ahead and release 0.9.

**Comment by mystor** [comment]
Given 0.9 has been published, closing.
