### ISSUE TITLE
Add diff.rs as an alternate mode for `cargo vet diff`

### ISSUE THREAD

**Issue by divergentdave** [mozilla/cargo-vet#624]
[diff.rs](https://diff.rs/) provides a single-page app to diff two `.crate` files, fetched from `crates.io`. Given that Sourcegraph has been unstable lately, I think it would be useful to add this as an alternative to `--mode=local` and `--mode=sourcegraph`. Note that this only shows diffs, so it wouldn't be appropriate for `cargo vet inspect`.

**Comment by mystor** [comment]
This has been fixed in #625
