### ISSUE TITLE
sourcegraph integration broken

### ISSUE THREAD

**Issue by RaphaelDarley** [mozilla/cargo-vet#628]
I'm using: cargo-vet 0.9.1
and every time I run a diff or inspect command I get repository not found from sourcegraph eg. cargo vet diff rustls 0.22.4 0.23.12 or cargo vet inspect atomic-waker 1.1.2.

<img width="738" alt="image" src="https://github.com/user-attachments/assets/547e3020-a644-4e84-91da-f4cb9705a70b">

**Comment by mystor** [comment]
I think this issue has already been reported in #611.

For now you can use `--local` to view diffs locally, and we'll release a new version with support for viewing diffs with https://diff.rs soon (#625).
